-- CreateTable
CREATE TABLE "WebHook" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdUserId" STRING NOT NULL,
    "createdUserName" STRING NOT NULL,
    "name" STRING NOT NULL,
    "url" STRING NOT NULL,
    "status" BOOL,

    CONSTRAINT "WebHook_pkey" PRIMARY KEY ("id")
);
