-- CreateTable
CREATE TABLE "Page" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdUserId" STRING NOT NULL,
    "createdUserName" STRING NOT NULL,
    "displayName" STRING NOT NULL,
    "apiName" STRING NOT NULL,

    CONSTRAINT "Page_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Field" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdUserId" STRING NOT NULL,
    "createdUserName" STRING NOT NULL,
    "fieldType" INT4 NOT NULL,
    "fieldName" STRING NOT NULL,
    "defaultValue" STRING NOT NULL,
    "isRequired" BOOL NOT NULL,
    "isShortText" BOOL NOT NULL,
    "value" STRING,
    "pageId" INT4 NOT NULL,

    CONSTRAINT "Field_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Field" ADD CONSTRAINT "Field_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
